// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { EventPassServiceCapacityInsightsData, EventPassServiceCapacityInsightsErrors, EventPassServiceCapacityInsightsResponses, EventPassServiceCreateData, EventPassServiceCreateErrors, EventPassServiceCreateResponses, EventPassServiceDeleteData, EventPassServiceDeleteErrors, EventPassServiceDeleteResponses, EventPassServiceGetData, EventPassServiceGetErrors, EventPassServiceGetResponses, EventPassServiceListData, EventPassServiceListErrors, EventPassServiceListResponses, EventPassServiceUpdateData, EventPassServiceUpdateErrors, EventPassServiceUpdateResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * List all event passes
 *
 * Returns all event pass records in the system.
 */
export const eventPassServiceList = <ThrowOnError extends boolean = false>(options?: Options<EventPassServiceListData, ThrowOnError>) => {
    return (options?.client ?? client).get<EventPassServiceListResponses, EventPassServiceListErrors, ThrowOnError>({
        url: '/',
        ...options
    });
};

/**
 * Create a new event pass
 *
 * Creates a new event pass record.
 */
export const eventPassServiceCreate = <ThrowOnError extends boolean = false>(options: Options<EventPassServiceCreateData, ThrowOnError>) => {
    return (options.client ?? client).post<EventPassServiceCreateResponses, EventPassServiceCreateErrors, ThrowOnError>({
        url: '/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Get event capacity insights
 *
 * Returns derived analytics about event capacity and registrations.
 */
export const eventPassServiceCapacityInsights = <ThrowOnError extends boolean = false>(options?: Options<EventPassServiceCapacityInsightsData, ThrowOnError>) => {
    return (options?.client ?? client).get<EventPassServiceCapacityInsightsResponses, EventPassServiceCapacityInsightsErrors, ThrowOnError>({
        url: '/capacity-insights',
        ...options
    });
};

/**
 * Delete an event pass
 *
 * Deletes an event pass by ID.
 */
export const eventPassServiceDelete = <ThrowOnError extends boolean = false>(options: Options<EventPassServiceDeleteData, ThrowOnError>) => {
    return (options.client ?? client).delete<EventPassServiceDeleteResponses, EventPassServiceDeleteErrors, ThrowOnError>({
        url: '/{id}',
        ...options
    });
};

/**
 * Get an event pass by ID
 *
 * Retrieves one event pass using its unique ID.
 */
export const eventPassServiceGet = <ThrowOnError extends boolean = false>(options: Options<EventPassServiceGetData, ThrowOnError>) => {
    return (options.client ?? client).get<EventPassServiceGetResponses, EventPassServiceGetErrors, ThrowOnError>({
        url: '/{id}',
        ...options
    });
};

/**
 * Partially update an event pass
 *
 * Updates one or more fields of an event pass.
 */
export const eventPassServiceUpdate = <ThrowOnError extends boolean = false>(options: Options<EventPassServiceUpdateData, ThrowOnError>) => {
    return (options.client ?? client).patch<EventPassServiceUpdateResponses, EventPassServiceUpdateErrors, ThrowOnError>({
        url: '/{id}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};
