// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://student-event-pass-manager-api-gxetbzfvfefdakeb.eastus-01.azurewebsites.net' | 'http://localhost:3000' | (string & {});
};

/**
 * Represents an event pass record.
 */
export type EventPass = {
    /**
     * Auto-generated unique identifier for the event pass
     */
    readonly id: string;
    /**
     * Name of the event
     */
    eventName: string;
    /**
     * Category of the event
     */
    category: 'Workshop' | 'Hackathon' | 'Seminar' | 'Networking' | 'CareerFair';
    /**
     * Location of the event
     */
    venue: string;
    /**
     * Scheduled event date
     */
    eventDate: string;
    /**
     * Maximum number of attendees allowed
     */
    capacity: number;
    /**
     * Number of attendees currently registered
     */
    registeredCount: number;
    /**
     * Type of pass issued for the event
     */
    passType: 'Free' | 'Standard' | 'VIP';
};

/**
 * Input schema for creating an event pass.
 */
export type EventPassCreate = {
    /**
     * Name of the event
     */
    eventName: string;
    /**
     * Category of the event
     */
    category: 'Workshop' | 'Hackathon' | 'Seminar' | 'Networking' | 'CareerFair';
    /**
     * Location of the event
     */
    venue: string;
    /**
     * Scheduled event date
     */
    eventDate: string;
    /**
     * Maximum number of attendees allowed
     */
    capacity: number;
    /**
     * Number of attendees currently registered
     */
    registeredCount: number;
    /**
     * Type of pass issued for the event
     */
    passType: 'Free' | 'Standard' | 'VIP';
};

/**
 * Input schema for partially updating an event pass.
 */
export type EventPassUpdate = {
    /**
     * Name of the event
     */
    eventName?: string;
    /**
     * Category of the event
     */
    category?: 'Workshop' | 'Hackathon' | 'Seminar' | 'Networking' | 'CareerFair';
    /**
     * Location of the event
     */
    venue?: string;
    /**
     * Scheduled event date
     */
    eventDate?: string;
    /**
     * Maximum number of attendees allowed
     */
    capacity?: number;
    /**
     * Number of attendees currently registered
     */
    registeredCount?: number;
    /**
     * Type of pass issued for the event
     */
    passType?: 'Free' | 'Standard' | 'VIP';
};

/**
 * Derived event capacity analytics.
 */
export type CapacityInsights = {
    /**
     * Total number of events
     */
    totalEvents?: number;
    /**
     * Number of events where registrations meet or exceed capacity
     */
    soldOutEvents?: number;
    /**
     * Number of events with fill rate of 80 percent or more
     */
    nearlyFullEvents?: number;
    /**
     * Average event fill rate across all events
     */
    averageFillRate?: number;
    /**
     * Events that are close to reaching full capacity
     */
    urgentEvents?: Array<UrgentEvent>;
    /**
     * Summary of event counts by category
     */
    categoryBreakdown?: Array<CategoryBreakdown>;
};

/**
 * Event that requires attention due to high occupancy.
 */
export type UrgentEvent = {
    id?: string;
    eventName?: string;
    fillRate?: number;
};

/**
 * Event count for one category.
 */
export type CategoryBreakdown = {
    category?: string;
    count?: number;
};

/**
 * Response after deleting an event pass.
 */
export type DeleteResponse = {
    /**
     * Delete confirmation message
     */
    message?: string;
};

/**
 * Standard error response.
 */
export type ErrorResponse = {
    /**
     * HTTP error status code
     */
    code?: number;
    /**
     * Error message
     */
    message?: string;
};

/**
 * Represents an event pass record.
 */
export type EventPassWritable = {
    /**
     * Name of the event
     */
    eventName: string;
    /**
     * Category of the event
     */
    category: 'Workshop' | 'Hackathon' | 'Seminar' | 'Networking' | 'CareerFair';
    /**
     * Location of the event
     */
    venue: string;
    /**
     * Scheduled event date
     */
    eventDate: string;
    /**
     * Maximum number of attendees allowed
     */
    capacity: number;
    /**
     * Number of attendees currently registered
     */
    registeredCount: number;
    /**
     * Type of pass issued for the event
     */
    passType: 'Free' | 'Standard' | 'VIP';
};

export type EventPassServiceListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type EventPassServiceListErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
};

export type EventPassServiceListError = EventPassServiceListErrors[keyof EventPassServiceListErrors];

export type EventPassServiceListResponses = {
    /**
     * A list of event passes
     */
    200: Array<EventPass>;
};

export type EventPassServiceListResponse = EventPassServiceListResponses[keyof EventPassServiceListResponses];

export type EventPassServiceCreateData = {
    body: EventPassCreate;
    path?: never;
    query?: never;
    url: '/';
};

export type EventPassServiceCreateErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
};

export type EventPassServiceCreateError = EventPassServiceCreateErrors[keyof EventPassServiceCreateErrors];

export type EventPassServiceCreateResponses = {
    /**
     * Event pass created successfully
     */
    201: EventPass;
};

export type EventPassServiceCreateResponse = EventPassServiceCreateResponses[keyof EventPassServiceCreateResponses];

export type EventPassServiceCapacityInsightsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/capacity-insights';
};

export type EventPassServiceCapacityInsightsErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
};

export type EventPassServiceCapacityInsightsError = EventPassServiceCapacityInsightsErrors[keyof EventPassServiceCapacityInsightsErrors];

export type EventPassServiceCapacityInsightsResponses = {
    /**
     * Capacity insight summary
     */
    200: CapacityInsights;
};

export type EventPassServiceCapacityInsightsResponse = EventPassServiceCapacityInsightsResponses[keyof EventPassServiceCapacityInsightsResponses];

export type EventPassServiceDeleteData = {
    body?: never;
    path: {
        /**
         * Unique identifier of the event pass
         */
        id: string;
    };
    query?: never;
    url: '/{id}';
};

export type EventPassServiceDeleteErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Event pass not found
     */
    404: ErrorResponse;
};

export type EventPassServiceDeleteError = EventPassServiceDeleteErrors[keyof EventPassServiceDeleteErrors];

export type EventPassServiceDeleteResponses = {
    /**
     * Event pass deleted successfully
     */
    200: DeleteResponse;
};

export type EventPassServiceDeleteResponse = EventPassServiceDeleteResponses[keyof EventPassServiceDeleteResponses];

export type EventPassServiceGetData = {
    body?: never;
    path: {
        /**
         * Unique identifier of the event pass
         */
        id: string;
    };
    query?: never;
    url: '/{id}';
};

export type EventPassServiceGetErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Event pass not found
     */
    404: ErrorResponse;
};

export type EventPassServiceGetError = EventPassServiceGetErrors[keyof EventPassServiceGetErrors];

export type EventPassServiceGetResponses = {
    /**
     * Event pass found
     */
    200: EventPass;
};

export type EventPassServiceGetResponse = EventPassServiceGetResponses[keyof EventPassServiceGetResponses];

export type EventPassServiceUpdateData = {
    body: EventPassUpdate;
    path: {
        /**
         * Unique identifier of the event pass
         */
        id: string;
    };
    query?: never;
    url: '/{id}';
};

export type EventPassServiceUpdateErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Event pass not found
     */
    404: ErrorResponse;
};

export type EventPassServiceUpdateError = EventPassServiceUpdateErrors[keyof EventPassServiceUpdateErrors];

export type EventPassServiceUpdateResponses = {
    /**
     * Event pass updated successfully
     */
    200: EventPass;
};

export type EventPassServiceUpdateResponse = EventPassServiceUpdateResponses[keyof EventPassServiceUpdateResponses];
