/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all event passes
         * @description Returns all event pass records in the system.
         */
        get: operations["EventPassService_list"];
        put?: never;
        /**
         * Create a new event pass
         * @description Creates a new event pass record.
         */
        post: operations["EventPassService_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/capacity-insights": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get event capacity insights
         * @description Returns derived analytics about event capacity and registrations.
         */
        get: operations["EventPassService_capacityInsights"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get an event pass by ID
         * @description Retrieves one event pass using its unique ID.
         */
        get: operations["EventPassService_get"];
        put?: never;
        post?: never;
        /**
         * Delete an event pass
         * @description Deletes an event pass by ID.
         */
        delete: operations["EventPassService_delete"];
        options?: never;
        head?: never;
        /**
         * Partially update an event pass
         * @description Updates one or more fields of an event pass.
         */
        patch: operations["EventPassService_update"];
        trace?: never;
    };
    "/{id}/tracking": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get tracking status for event logistics
         * @description Returns mocked logistics tracking from a third-party shipping service.
         */
        get: operations["EventPassService_tracking"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/students/{studentId}/recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get personalized event recommendations
         * @description Returns mocked recommendations from a third-party recommendation service.
         */
        get: operations["StudentService_recommendations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Represents an event pass record.
         * @example {
         *       "id": "evt_001",
         *       "eventName": "Scarlet Hacks Kickoff",
         *       "category": "Hackathon",
         *       "venue": "Downtown Campus Room 470",
         *       "eventDate": "2026-04-04",
         *       "capacity": 300,
         *       "registeredCount": 275,
         *       "passType": "Free"
         *     }
         */
        EventPass: {
            /** @description Auto-generated unique identifier for the event pass */
            readonly id: string;
            /** @description Name of the event */
            eventName: string;
            /**
             * @description Category of the event
             * @enum {string}
             */
            category: "Workshop" | "Hackathon" | "Seminar" | "Networking" | "CareerFair";
            /** @description Location of the event */
            venue: string;
            /**
             * Format: date
             * @description Scheduled event date
             */
            eventDate: string;
            /**
             * Format: int32
             * @description Maximum number of attendees allowed
             */
            capacity: number;
            /**
             * Format: int32
             * @description Number of attendees currently registered
             */
            registeredCount: number;
            /**
             * @description Type of pass issued for the event
             * @enum {string}
             */
            passType: "Free" | "Standard" | "VIP";
        };
        /** @description Input schema for creating an event pass. */
        EventPassCreate: {
            /** @description Name of the event */
            eventName: string;
            /**
             * @description Category of the event
             * @enum {string}
             */
            category: "Workshop" | "Hackathon" | "Seminar" | "Networking" | "CareerFair";
            /** @description Location of the event */
            venue: string;
            /**
             * Format: date
             * @description Scheduled event date
             */
            eventDate: string;
            /**
             * Format: int32
             * @description Maximum number of attendees allowed
             */
            capacity: number;
            /**
             * Format: int32
             * @description Number of attendees currently registered
             */
            registeredCount: number;
            /**
             * @description Type of pass issued for the event
             * @enum {string}
             */
            passType: "Free" | "Standard" | "VIP";
        };
        /** @description Input schema for partially updating an event pass. */
        EventPassUpdate: {
            /** @description Name of the event */
            eventName?: string;
            /**
             * @description Category of the event
             * @enum {string}
             */
            category?: "Workshop" | "Hackathon" | "Seminar" | "Networking" | "CareerFair";
            /** @description Location of the event */
            venue?: string;
            /**
             * Format: date
             * @description Scheduled event date
             */
            eventDate?: string;
            /**
             * Format: int32
             * @description Maximum number of attendees allowed
             */
            capacity?: number;
            /**
             * Format: int32
             * @description Number of attendees currently registered
             */
            registeredCount?: number;
            /**
             * @description Type of pass issued for the event
             * @enum {string}
             */
            passType?: "Free" | "Standard" | "VIP";
        };
        /** @description Derived event capacity analytics. */
        CapacityInsights: {
            /** @description Total number of events */
            totalEvents?: number;
            /** @description Number of events where registrations meet or exceed capacity */
            soldOutEvents?: number;
            /** @description Number of events with fill rate of 80 percent or more */
            nearlyFullEvents?: number;
            /** @description Average event fill rate across all events */
            averageFillRate?: number;
            /** @description Events that are close to reaching full capacity */
            urgentEvents?: components["schemas"]["UrgentEvent"][];
            /** @description Summary of event counts by category */
            categoryBreakdown?: components["schemas"]["CategoryBreakdown"][];
        };
        /** @description Event that requires attention due to high occupancy. */
        UrgentEvent: {
            id?: string;
            eventName?: string;
            fillRate?: number;
        };
        /** @description Event count for one category. */
        CategoryBreakdown: {
            category?: string;
            count?: number;
        };
        /** @description Response after deleting an event pass. */
        DeleteResponse: {
            /** @description Delete confirmation message */
            message?: string;
        };
        /** @description Standard error response. */
        ErrorResponse: {
            /** @description HTTP error status code */
            code?: number;
            /** @description Error message */
            message?: string;
        };
        /** @description Third-party logistics tracking response. */
        TrackingInfo: {
            eventId: string;
            provider: string;
            trackingId: string;
            /** @enum {string} */
            status: "CREATED" | "SCHEDULED" | "IN_TRANSIT" | "DELIVERED" | "DELAYED";
            /** Format: date-time */
            estimatedArrival: string;
            /** Format: date-time */
            lastUpdated: string;
        };
        /** @description One recommended event from third-party recommendation service. */
        Recommendation: {
            id: string;
            title: string;
            reason: string;
            score: number;
        };
        /** @description Recommendation payload for a student. */
        RecommendationResponse: {
            studentId: string;
            source: string;
            recommendations: components["schemas"]["Recommendation"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    EventPassService_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A list of event passes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventPass"][];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    EventPassService_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventPassCreate"];
            };
        };
        responses: {
            /** @description Event pass created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventPass"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    EventPassService_capacityInsights: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Capacity insight summary */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CapacityInsights"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    EventPassService_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier of the event pass */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Event pass found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventPass"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Event pass not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    EventPassService_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier of the event pass */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Event pass deleted successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Event pass not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    EventPassService_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier of the event pass */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventPassUpdate"];
            };
        };
        responses: {
            /** @description Event pass updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventPass"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Event pass not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    EventPassService_tracking: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier of the event pass */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tracking details returned successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrackingInfo"];
                };
            };
            /** @description Event pass not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    StudentService_recommendations: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier of the student */
                studentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recommendations returned successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationResponse"];
                };
            };
            /** @description Student not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
